#!/usr/bin/env bash
# Inject AppDir conventions into a Tauri-built AppImage and repack it.
#
# Why: the AppImage catalog (appimage.github.io) mounts every submitted
# AppImage and runs appdir-lint.sh, which FATALs when `.DirIcon` is missing.
# tauri-bundler creates `.DirIcon`, the root icon (`<Icon>.png`) and the root
# `.desktop` symlink in the AppDir before handing it to linuxdeploy, but the
# linuxdeploy build pinned by the bundler strips them while repacking — the
# final AppImage loses all three. This script extracts the squashfs image,
# re-injects the files, repacks with appimagetool, and verifies the result.
#
# Usage: scripts/fix-appimage-appdir.sh <path/to/AppImage>
# Env:   APPIMAGETOOL_URL — override the pinned appimagetool download
#
# The repack changes the file bytes, so any updater signature generated by
# `tauri build` is stale afterwards; the caller must re-sign
# (`tauri signer sign`) when updater artifacts are enabled.
set -euo pipefail

APPIMAGE="${1:?usage: fix-appimage-appdir.sh <AppImage>}"
APPIMAGETOOL_URL="${APPIMAGETOOL_URL:-https://github.com/AppImage/appimagetool/releases/download/1.9.1/appimagetool-x86_64.AppImage}"

if [ ! -f "$APPIMAGE" ]; then
  echo "error: AppImage not found: $APPIMAGE" >&2
  exit 1
fi
chmod +x "$APPIMAGE"
APPIMAGE_ABS="$(cd "$(dirname "$APPIMAGE")" && pwd)/$(basename "$APPIMAGE")"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# ── 1) Extract the squashfs image (runtime's built-in extractor, no FUSE) ──
(cd "$WORK" && "$APPIMAGE_ABS" --appimage-extract > /dev/null)
ROOT="$WORK/squashfs-root"
if [ ! -d "$ROOT" ]; then
  echo "error: --appimage-extract produced no squashfs-root" >&2
  exit 1
fi

# ── 2) Re-inject what linuxdeploy dropped ──
# Desktop file under usr/share/applications is the source of truth for the
# Icon= name; appdir-lint requires EXACTLY ONE .desktop file at the AppDir
# root, and worker.sh resolves the icon from Icon=.
DESKTOP_SRC="$(find "$ROOT/usr/share/applications" -maxdepth 1 -name '*.desktop' 2>/dev/null | head -n 1)"
if [ -z "$DESKTOP_SRC" ]; then
  echo "error: no .desktop file under usr/share/applications" >&2
  exit 1
fi
DESKTOP_NAME="$(basename "$DESKTOP_SRC")"
ICON_NAME="$(grep -m1 '^Icon=' "$DESKTOP_SRC" | cut -d= -f2- | tr -d '\r')"
if [ -z "$ICON_NAME" ]; then
  echo "error: $DESKTOP_NAME has no Icon= entry" >&2
  exit 1
fi

# Root icon must be a PNG so .DirIcon thumbnails work (appdir-lint warns on
# non-PNG). Reuse the root copy if it survived, else take the largest
# deployed hicolor icon.
ROOT_ICON="$ROOT/$ICON_NAME.png"
if [ ! -e "$ROOT_ICON" ]; then
  BEST_ICON="$(find "$ROOT/usr/share/icons" -name "$ICON_NAME.png" 2>/dev/null | sort -V | tail -n 1)"
  if [ -z "$BEST_ICON" ]; then
    echo "error: no $ICON_NAME.png found under usr/share/icons" >&2
    exit 1
  fi
  cp "$BEST_ICON" "$ROOT_ICON"
fi

# .DirIcon: relative symlink to the root PNG (relative so it resolves inside
# the mounted/extracted image regardless of the mount point).
ln -sfn "$ICON_NAME.png" "$ROOT/.DirIcon"

# Keep exactly one root desktop entry: drop foreign leftovers, then make sure
# ours exists (symlink target is relative to the AppDir root).
for stray in "$ROOT"/*.desktop; do
  [ -e "$stray" ] || continue
  [ "$(basename "$stray")" = "$DESKTOP_NAME" ] || rm -f "$stray"
done
if [ ! -e "$ROOT/$DESKTOP_NAME" ]; then
  ln -s "usr/share/applications/$DESKTOP_NAME" "$ROOT/$DESKTOP_NAME"
fi

# ── 3) Repack with a pinned appimagetool ──
# --appimage-extract-and-run keeps this working without FUSE on the runner;
# -n skips AppStream validation (Tauri ships no metainfo yet).
TOOL="$WORK/appimagetool.AppImage"
if [ -n "${APPIMAGETOOL_FILE:-}" ]; then
  cp "$APPIMAGETOOL_FILE" "$TOOL"
else
  curl -fsSL --retry 3 -o "$TOOL" "$APPIMAGETOOL_URL"
fi
chmod +x "$TOOL"
"$TOOL" --appimage-extract-and-run -n "$ROOT" "$APPIMAGE_ABS"

# ── 4) Verify the repacked image from a clean extract ──
(cd "$WORK" && rm -rf squashfs-root && "$APPIMAGE_ABS" --appimage-extract > /dev/null)
if [ ! -e "$ROOT/.DirIcon" ]; then
  echo "error: .DirIcon still missing after repack" >&2
  exit 1
fi
if [ ! -e "$ROOT/$ICON_NAME.png" ]; then
  echo "error: root icon $ICON_NAME.png still missing after repack" >&2
  exit 1
fi
DESKTOP_COUNT="$(find "$ROOT" -maxdepth 1 -name '*.desktop' | wc -l | tr -d ' ')"
if [ "$DESKTOP_COUNT" != "1" ]; then
  echo "error: expected exactly 1 root .desktop after repack, got $DESKTOP_COUNT" >&2
  exit 1
fi
if [ ! -x "$ROOT/AppRun" ]; then
  echo "error: AppRun missing or not executable after repack" >&2
  exit 1
fi

echo "✓ AppImage AppDir fixed: $APPIMAGE_ABS (.DirIcon → $ICON_NAME.png, desktop: $DESKTOP_NAME)"
